version: "3"

services:

  database:
    container_name: shimpyo-db
    image: mariadb:10
    environment:
      MARIADB_DATABASE: shimpyo
      MARIADB_ROOT_HOST: ${DB_ROOT_HOST}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - ./mariadb/config:/etc/mysql/conf.d
      - ./mariadb/data:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"
    restart: unless-stopped


  redis:
    container_name: shimpyo-redis
    image: redis:6
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/config:/usr/local/conf/redis.cnf
      - ./redis/data:/data
    labels:
      - "name=redis"
      - "mode=standalone"
    restart: on-failure


networks:
  shimpyo_network:
