spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/shimpyo?createDatabaseIfNotExist=true&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update