spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/shimpyo?createDatabaseIfNotExist=true&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    redis:
      port: 6379
      host: localhost
jwt:
  secret: 7Yyo7Iqk7Yq47Lqg7Y287IqkIOuvuOuLiO2UhOuhnOygne2KuCAxMeyhsCDsibztkZwgSldUIOyLnO2BrOumvyDtgqQ=
  access-token-expire-time: 1800000
  refresh-token-expire-time: 604800000