name: CD with Gradle

on:
  push:
    branches: [ "main", "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: "adopt"

      - name: Make application.properties
        run: |
          echo "${{ secrets.LOCAL_PROPERTIES }}" | base64 --decode > src/main/resources/application-local.yml
          echo "${{ secrets.PROD_PROPERTIES }}" | base64 --decode > src/main/resources/application-prod.yml
          echo "${{ secrets.TEST_PROPERTIES }}" | base64 --decode > src/test/resources/application.yml

      - name: Make env file
        run: |
          echo "${{ secrets.ENV }}" | base64 --decode > .env

      - name: Grant execute permission for gradlew
        run: |
          chmod +x gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.6.0
        with:
          arguments: build

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        id: deploy
        with:
          host: ${{ secrets.HOST }} | base64 --decode
          username: ubuntu
          key: ${{ secrets.KEY }} | base64 --decode
          envs: GITHUB_SHA
          script: |
            git pull origin develop
            ./gradlew build
            chmod 755 ./mariadb/config/my.cnf
            chmod 755 ./redis/config/redis.cnf
            docker-compose up --build
